# Build java application for gather and persistent save of sprint statistics data

before_install:
  # Set Gradle builder executable permissions
  - chmod +x gradlew

language: java
install: true
jdk: openjdk11

script:
  # Use Gradle as tester
  - ./gradlew test
  # Trigger with Gradle static and dynamic code analysis
  - ./gradlew jacocoTestReport sonarqube
